class Solution:
    def carFleet(self, target: int, position: List[int], speed: List[int]) -> int:
        pair = [[p, s] for p, s in zip(position, speed)]  # list comprehension in python, creates new list (of lists) based on existing iterables. 
        stack = []  # if fleet it will be pushed here and then at the end we will simply get the lenght of this stack to get the total number of fleets.

        for p, s in sorted(pair)[::-1]:  # Reverse Order traversal. Since we sorted it as well so it will be Reverse Sorted Traversal.
            stack.append((target - p) / s)  # append the time the call will take to its destination to the stack.
            if len(stack) >= 2 and stack[-1] <= stack[-2]:  # checking if 1) Stack has at least two cars as if its just one no collision possible, and 2) if the time for car at the top of the stack ie stack[-1] is the same or less than as stack[-2] the car IN FRONT of it (remember reverse sorting) that must mean that they collide!
                stack.pop()  # so in that case we have to pop it, and this reduces the length of the stack. We dont do this if the above conditions are not met.
        return len(stack)








"""This is what zip(l1, l2) does 
The syntax pair = [[p, s] for p, s in zip(position, speed)] is a list comprehension that creates a list of lists. 
It pairs corresponding elements from two iterables, position and speed, using the zip function, which produces tuples of these elements. 
For each tuple (p, s) generated by zip, it creates a list [p, s]. The resulting pair list contains these lists of paired elements, effectively combining position and speed element-wise into a new list of lists. 
For example, with position = [1, 2, 3] and speed = [4, 5, 6], the result will be [[1, 4], [2, 5], [3, 6]]."""

"""Another way to sort or sort reverse is by simply doing: pair.sort(reverse=True) """